### DISCUSSION TITLE
Use the same Orchard Core headless app between environments: same database and two running environment, one in Docker and the other in Visual Studio

### DISCUSSION THREAD

**Discussion by MarGraz** [OrchardCMS/OrchardCore#15562] [Q&A] [answered]
Hi everyone,

I'm developing some headless microservices within the same solution, and I'm trying to use the same database that is running in my "Docker desktop", for the same Orchard Core app (I will call it A here):

- The Orchard Core app (A) running in Docker, utilized for testing other microservices;
- The Orchard Core app (A) running in Visual Studio, utilized for developing the microservice itself.

The database is internally exposed by Docker, and also made available to the `localhost` for Visual Studio use, with the port set to 12208.

**The first time I started my app (A), I configured running it through Docker**. Now, I'm attempting to use the same database with the app (A) running in Visual Studio, but each time it starts, the "initial configuration" page of Orchard Core appears, as if it's a first run and the database is not set up. 

Upon checking the documentation, I noticed the `App_Data` folder is implicated in this initial setup, as mentioned [here](https://docs.orchardcore.net/en/main/docs/reference/core/Configuration/#global-tenant-data-access-configuration). However, simply copying and pasting this folder from Docker, to my Visual Studio folder didn't solve the issue. The "initial configuration" page still appears.

I've tried configuring the `appsettings.Development.json` in two different ways, **this one always results in the "initial configuration" page**:

```json
{
  "OrchardCore": {
    "ConnectionString": "Server=localhost;Port=12208;Database=*******;User Id=*******;Password=********",
    "DatabaseProvider": "Postgres"
  }
}
```

This one instead **ends in a 404 http error**:

```json
{
  "OrchardCore": {
    "ConnectionString": "Server=localhost;Port=12208;Database=*******;User Id=*******;Password=********",
    "DatabaseProvider": "Postgres",
    "Default": {
      "State": "Running",
      "TablePrefix": "Default"
    }
  }
}
```

Note that to create my Orchard Core app, I used the "[code generation template](https://docs.orchardcore.net/en/main/docs/getting-started/templates/)" available in Visual Studio, in the template list it appears as "Orchard Core CMS Web App".

The question is: **how can I use the same Orchard Core headless app, across environments, with the same database?**

Thank you

**Comment by MarGraz** [comment]
I've done a comparison between the `App_Data` folder in my **Docker** microservice, and the `App_Data` folder of a project I started **locally**. 

Those are two different projects, both using Orchard Core 1.8.2. They use two different databases, Docker uses `PostgreSQL`, while the local project uses `SQL Server`.

**Below are some screenshots for comparison**, where:

- **On the left**: `Local` project
- **On the right**: `Docker` project

**Starting with the `tenants.json`** file comparison, **note that** the local version includes a `State` property absent in the Docker version. Additionally, in the Docker version, the two IDs are the same.

![tenants.json comparison](https://github.com/OrchardCMS/OrchardCore/assets/19241483/4db005a2-5cf5-4af8-bbac-65b1b706a91c)

This screenshot show **the contents of the `App_Data` > `Sites` > `Default` folder**:

![image](https://github.com/OrchardCMS/OrchardCore/assets/19241483/bf5cb36e-63f4-46a7-8130-604380f464fb)

Next, we look at **what's inside the `appsettings.json`**. Note that the Docker version is empty:

![appsettings.json contents](https://github.com/OrchardCMS/OrchardCore/assets/19241483/cd3ac961-ff00-4952-b408-75c9053525ad)

Finally, this screenshot displays **the XML file inside the `DataProtection-Keys` folder**:

![DataProtection-Keys XML file](https://github.com/OrchardCMS/OrchardCore/assets/19241483/5247d625-bcad-4209-aa0c-d3a4507a342b)

**My question is**: why are the `App_Data` files `tenants.json` and `appsettings.json` different between the Docker and local versions? While my Docker setup runs perfectly on Docker Desktop, attempting to run it in Visual Studio with the same `App_Data` folder, results in the Orchard Core "initial configuration" page appearing, prompting for database and site information.

@Piedone is there someone from Lombiq that could clarify this situation and advise on how to configure both environments for the same Orchard Core site? Could this be indicative of a bug?

Thank you so much

**Comment by Piedone** [comment]
Upon launch, OC will check the App_Data folder for tenant settings, unless you use one of the [other Shells Configuration Providers](https://docs.orchardcore.net/en/latest/docs/reference/core/Shells/)). If none are found, it'll show you the setup screen. If a matching one is found, it'll try to connect to its configured DB; if there are any issues after this, startup will fail.

Your screenshots suggest that the Docker version of the app is running a different Shells Configuration Provider. Didn't you configure that?

BTW I believe in your original question you meant app B for the VS one.

**Reply by MarGraz** [reply, marked as answer]
@Piedone thank you for your reply 😊

No, **in my original question, I was referring to the Orchard Core app "A" for both Docker and Visual Studio**. This is because I need to develop and debug the Orchard Core app and I need Visual Studio, but in the meantime, another instance of this Orchard Core app "A" is running on a local Docker Desktop, where I'm testing it with other microservices. Of course I update the Docker image every time I have new code in the Visual Studio app "A" version.

No, **I haven't configured different** "[Shells Configuration Providers](https://docs.orchardcore.net/en/latest/docs/reference/core/Shells/)".

**In conclusion, I was able to use the same Orchard Core headless app across both environments**, Docker and Visual Studio, with the same database in this way:

- The PostgreSQL server is running on Docker and is also exposed to `localhost`;
- Both Orchard Core apps "A" are using the same `App_Data` folder located in my local Visual Studio solution, on my hard drive (**see the variable in the yaml `BE_SOLUTION_PATH`**);
- I added an `appsettings.Development.json` file to my project.

This is how my `yaml` template looks like:

```yaml
version: "3.8"
services:
  be-myservice:
    build:
      dockerfile: MyProjectName.MyMicroserviceName/Dockerfile
      context: ${BE_SOLUTION_PATH}
    restart: always
    environment:
      - OrchardCore__DatabaseProvider=Postgres
      - OrchardCore__ConnectionString=Server=be-myservice-postgres;Port=12190;Database=${POSTGRES_DATABASE};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ORCHARD_APP_DATA=/app/orchard-data/App_Data
      # - OrchardCore__Default__State=Running
      # - OrchardCore__Default__TablePrefix=Default
    volumes:
      - ${BE_SOLUTION_PATH}/MyProjectName.MyMicroserviceName:/app/orchard-data
    ports:
      - 12190:8080
    depends_on:
      - be-myservice-postgres

  be-myservice-postgres:
    image: postgres:latest
    restart: always
    volumes:
      - bemyservicepostgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=12190
    ports:
      - 12190:12190

volumes:
  bemyservicepostgresdata:
    driver: local
```

**Note that** `MyProjectName.MyMicroserviceName`, `be-myservice`, and `be-myservice-postgres` are invented names to be replaced with your app or service names. Database volumes are hosted inside Docker where the Posgre SQL Server is running, and the `App_Data` used for both apps "A" is the one in my local Visual Studio solution, on my hard drive, as explained before.

This is how the `appsettings.Development.json` looks like:

```json
{
  "OrchardCore": {
    "DatabaseProvider": "Postgres",
    "ConnectionString": "Server=localhost;Port=12190;Database={here your DB name};User Id={here your DB username};Password={here the password}"
  }
}
```

Thank you
