### DISCUSSION TITLE
Deploying to Azure App Services - Windows

### DISCUSSION THREAD

**Discussion by weirdyang** [OrchardCMS/OrchardCore#9438] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/25576022/118304300-13724d80-b519-11eb-86f8-76274f31f28d.png)
```
Package deployment using ZIP Deploy initiated.
Successfully deployed web package to App Service.
NOTE: Run From Package makes wwwroot read-only, so you will receive an error when writing files to this directory.
Successfully updated App Service configuration details
App Service Application URL: http://arcflow-uat.azurewebsites.net

```

I'm want to use Azure DevOps pipeline to deploy my project to Azure App service. However I am unable to write file to the wwwroot using the the package zip deploy. Which method should I be using?

**Comment by deanmarcussen** [comment]
WebDeploy.

You can'y use Run As Package

**Reply by weirdyang** [reply]
Thanks.

Is this correct? I use a folder instead of zip?

```
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: ------------
    appType: 'webApp'
    WebAppName: 'test-uat'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/publish/'
```

```
 # deploymentMethod: zipDeploy
```
there's only 2 options and I was using zip Deploy.
