### ISSUE TITLE
Markdown rich editor corrupts Arabic text in OC  1.4

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#12172]
### Describe the bug

The Arabic text in this rich editor is corrupted

![mde-markdown](https://user-images.githubusercontent.com/1761249/183933380-8b57ca94-90b6-451d-b986-b42d7bbc71e8.png)

This is the text on the same exact field without the rich editor

![mde-markdown-1](https://user-images.githubusercontent.com/1761249/183932525-b1545716-08e3-4bb1-8329-301f6bacb301.png)

**Comment by Skrypt** [comment]
Have you tried directly with the same text and the markdown editor on their website demo?

**Comment by dodyg** [comment]
Good idea let me try it

**Comment by dodyg** [comment]
This is the corrupted data in EasyMDE

![corrupt](https://user-images.githubusercontent.com/1761249/183940240-43d6890a-8150-4342-bd50-45a4df34d561.png)

This is the actual rendering

https://try.orchardcore.net/wmuhsxod/blog/post-1

The website is https://try.orchardcore.net/wmuhsxod
Username: admin
Password: ?B002t-L 

If anyone wants to replicate

**Comment by dodyg** [comment]
`برنامج مؤسسة ساويرس للحصول على الدبلوم الفني الفندقي من المدرسة الألمانية الفندقية بالجونة`

There is no problem with the EasyMDE itself (https://easy-markdown-editor.tk/)

![easy-mark](https://user-images.githubusercontent.com/1761249/183944613-f22926dd-f0c0-4765-bc95-fea7a79ce6d2.png)

But at OC14, the text becomes corrupted
![easy-mark-2](https://user-images.githubusercontent.com/1761249/183944646-cf675aa5-8992-4e3c-ba73-c8622f6510a3.png)

**Comment by dodyg** [comment]
The editor in OC 1.4 is the same version as https://easy-markdown-editor.tk/
![easy-mark-3](https://user-images.githubusercontent.com/1761249/183945096-1afd894c-d5da-43c8-92f2-2f9611363559.png)

**Comment by Skrypt** [comment]
I see the text is reversed in the editor.

**Comment by Skrypt** [comment]
I just found this repository which probably indicates that EasyMDE has issues with RTL.
https://github.com/imAbdelhadi/easymde-rtl

**Comment by Skrypt** [comment]
@dodyg I think we could bundle the RTL version in OC and switch to it based on CultureInfo RTL.

**Comment by hishamco** [comment]
Seems I come late to fix the Arabic issue ;) from the first time I saw the text, the letters in the words have been revered, so we could fix this as @Skrypt suggested before

@dodyg is it working before OC 1.4 or the issue from the beginning because no one tried Arabic text ;)

**Comment by dodyg** [comment]
@hishamco I can't remember but the site was already English/Arabic since OC 1.0 and this was the first complain regarding reverse text.

**Comment by Skrypt** [comment]
Maybe a BS 5 upgrade regression. If this can be fixed by changing only styles then it will be better. I didn't find where it is reversing the text.

**Comment by hishamco** [comment]
I might look into this

**Comment by dodyg** [comment]
The culprit is in TheAdmin.css

![style-1](https://user-images.githubusercontent.com/1761249/184480751-29bbf998-08be-42f9-8e51-0839c832c733.png)
![style-2](https://user-images.githubusercontent.com/1761249/184480752-5d1833b5-397c-46b5-a0b5-bebffef025a2.png)

**Comment by dodyg** [comment]
I found the problem. 

`ltr` here
![problem-1](https://user-images.githubusercontent.com/1761249/184485326-317cc141-91ec-4771-a7b2-bde38998fb11.png)

Changing it to `rtl` fix it.
![problem-2](https://user-images.githubusercontent.com/1761249/184485410-dbdba647-641d-445f-be32-f80b04b137ca.png)

**Comment by dodyg** [comment]
This is most likely the problematic css in TheAdmin.css file. There is a comment about `rtl:ignore`. I am not sure what the reason is.  Maybe people more familiar with the theme can review this.

```css
html[data-theme=default] pre,
html[data-theme=default] code,
html[data-theme=default] kbd,
html[data-theme=default] samp {
  font-family: var(--bs-font-monospace);
  font-size: 1em;
  direction: ltr /* rtl:ignore */;
  unicode-bidi: bidi-override;
}
```

https://raw.githubusercontent.com/OrchardCMS/OrchardCore/main/src/OrchardCore.Themes/TheAdmin/wwwroot/css/TheAdmin.css

**Comment by hishamco** [comment]
I think from the style author, unless @Skrypt did it for a reason

**Comment by dodyg** [comment]
![bidi](https://user-images.githubusercontent.com/1761249/184501317-0f2a18ac-d146-4d80-b6bb-c64f56af893e.png)

The direction is really not necessary if the `unicode-bidi: bidi-override;` is removed.

``` css
  direction: ltr /* rtl:ignore */;
  unicode-bidi: bidi-override;
```

**Comment by dodyg** [comment]
This thing is like hydra. Once the `unicode-bidi` removed, the codemirror.min.css needs to be dealt with.

![code-mirror](https://user-images.githubusercontent.com/1761249/184501951-b2f30ae8-26d4-477a-9da8-5af4824d4c39.png)

**Comment by dodyg** [comment]
One possible solution is changing

``` css
html[data-theme=default] pre,
html[data-theme=default] code,
html[data-theme=default] kbd,
html[data-theme=default] samp {
  font-family: var(--bs-font-monospace);
  font-size: 1em;
  direction: ltr /* rtl:ignore */;
  unicode-bidi: bidi-override;
}
```

to 

``` css

html[data-theme=default] pre,
html[data-theme=default] code,
html[data-theme=default] kbd,
html[data-theme=default] samp {
  font-family: var(--bs-font-monospace);
  font-size: 1em;
}

html[dir=ltr][data-theme=default] pre,
html[dir=ltr][data-theme=default] code,
html[dir=ltr][data-theme=default] kbd,
html[dir=ltr][data-theme=default] samp {
    direction: ltr !important;
}

html[dir=rtl][data-theme=default] pre,
html[dir=rtl][data-theme=default] code,
html[dir=rtl][data-theme=default] kbd,
html[dir=rtl][data-theme=default] samp {
    direction: rtl !important;
}
```

**Comment by dodyg** [comment]
Above solution works on Microsoft Edge

![edge](https://user-images.githubusercontent.com/1761249/184634581-c5e7b92c-149a-4ef6-9549-71efc429a562.png)

Firefox
![firefox](https://user-images.githubusercontent.com/1761249/184634623-3090cc44-58a5-44a4-92ec-af97f1444444.png)

but not Google Chrome

![chrome](https://user-images.githubusercontent.com/1761249/184634652-7623b409-1f5b-438d-89eb-1428e5725dfa.png)

**Comment by Skrypt** [comment]
Have you tried removing only the `/*rtl:ignore*/` comment?
Also, make sure you test with different RTL cultures afterward because it seems like it works for other people.

**Comment by dodyg** [comment]
Hebrew

![hebrew-1](https://user-images.githubusercontent.com/1761249/184874725-af9ab621-b523-4ab4-ad08-68de3740115f.png)
![hebrew-2](https://user-images.githubusercontent.com/1761249/184874732-5c1dcaa7-ac05-4fab-af41-a334e3e382e6.png)

Site: https://try.orchardcore.net/2z5kxzxk
username: admin
password: _Y73koqP

**Comment by dodyg** [comment]
This is how the Hebrew posting supposed to be. I had to modify the RTL directly.

![supposed-to-be](https://user-images.githubusercontent.com/1761249/184875094-5a27d4d4-9491-4846-a1b3-5b84b9276f1e.png)

I am not sure what's the purpose of removing `/*rtl:ignore*/` because it doesn't really show up at the inspector.

**Comment by dodyg** [comment]
I don't understand why the `unicode-bidi: bidi-override;` is required. Because if you remove this, the `direction` can be removed.

```css

html[data-theme=default] pre,
html[data-theme=default] code,
html[data-theme=default] kbd,
html[data-theme=default] samp {
  font-family: var(--bs-font-monospace);
  font-size: 1em;
  direction: ltr /* rtl:ignore */;
  unicode-bidi: bidi-override;
}
```
