### ISSUE TITLE
Github actions The 'Publish' target is not supported without specifying a target framework. 

### ISSUE THREAD

**Issue by Cinnam00n** [OrchardCMS/OrchardCore#12170]
### Describe the bug
Github actions pipeline throws a build error:

` The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, you must specify the framework for the published application. `

### To Reproduce
Contents of .yml file:
```
name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.101'
          include-prerelease: true

      - name: Build with dotnet
        run: |
          dotnet restore
          dotnet build --configuration Release --framework net6.0
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
   [ ... ]
```

### Expected behavior
The application builds successfully. The exact same branch builds and runs from VS without a problem.
