### ISSUE TITLE
Frontend assets are outdated

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#15726]
### Describe the bug

The `assets_validation` workflow didn't catch this, because it has a bug, but if you [build the frontend assets](https://docs.orchardcore.net/en/latest/docs/guides/gulp-pipeline/) then there will be changed files. This means that when you run OC, the client-side assets are actually outdated.

See a correctly failing `assets_validation` [here](https://github.com/OrchardCMS/OrchardCore/actions/runs/8638115705).

Once https://github.com/OrchardCMS/OrchardCore/pull/15619 is merged, `assets_validation` will be fixed.

### To Reproduce

In the root of the repo:

1. `npm install`
2. `gulp rebuild`

### Expected behavior
No files changed.

Also, we should run `assets_validation` as a CI workflow too, this shouldn't be just on-demand. So, add the following triggers to it:

```
on: 
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    branches: [ main ]
  pull_request:
    branches: [ main, release/** ]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
```

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/1976647/f09fd0a7-ba8c-417f-baa7-ebf46c725073)
