### ISSUE TITLE
Unable to Store OrchardCore.Media.Azure Connection Strings in Azure KeyVault

### ISSUE THREAD

**Issue by JoshLefebvre** [OrchardCMS/OrchardCore#6359]
I am trying to store some of my appsettings value in my Azure KeyVault for security purposes, however due to the current naming conventions used in the appsettings.json files I am unable to due to illegal dot characters in some of the setting names:
![image](https://user-images.githubusercontent.com/22512098/83955830-4f8b3180-a825-11ea-88ad-5c0902895918.png)

From the Azure Documentation:

> Colons, which are normally used to delimit a section from a subkey in ASP.NET Core configuration, aren't allowed in key vault secret names. Therefore, two dashes are used and swapped for a colon when the secrets are loaded into the app's configuration.

As far as I know there aren't any similar configurations to allow . (periods) in azure keyvault names. Has anyone figured out a workaround for this without having to overload IKeyVaultSecretManager ?

**Comment by jtkech** [comment]
We also allow underscores (which is the new rule) in place of dots, this to be compatible with linux env variables, so try the following

    OrchardCore_Media_Azure--ConnectionString

**Comment by JoshLefebvre** [comment]
Yea Az Key Vault is still complaining:
![image](https://user-images.githubusercontent.com/22512098/83957310-34282280-a835-11ea-9352-127dbcd1a710.png)
Seems only dashes and alpha numeric.

**Comment by JoshLefebvre** [comment]
Do you think it would be worth filing a change request ?

**Comment by jtkech** [comment]
> Do you think it would be worth filing a change request ?

Yes i think it is worth to have an override of [KeyVaultSecretManager](https://github.com/Azure/azure-sdk-for-net/blob/779ddcd153436ce9105c6d3765463e3da26d52d3/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/KeyVaultSecretManager.cs#L24), and maybe an extension helper using [AddAzureKeyVault](https://github.com/Azure/azure-sdk-for-net/blob/779ddcd153436ce9105c6d3765463e3da26d52d3/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationExtensions.cs#L25), e.g. `AddOrchardCoreAzureKeyVault()` that we could use at the app level.

This through a separate package e.g. `OrchardCore.Azure.KeyVault` as we don't want to reference azure packages from the app by default, as we do for `OrchardCore.Shells.Azure`

**Comment by JoshLefebvre** [comment]
Awesome! I realize you guys are quite busy and this might be low on the priority list so I will start my own repo (as I have done with many other custom modules I am developing) with an implementation and if it is something that may be of interest I would be happy to integrate it into the project!

Thanks :)

**Comment by JoshLefebvre** [comment]
So I have done a bit more research into understanding and developing a custom implementation of IKeyVaultSecretManager. 

> The DefaultKeyVaultSecretManager replaces double-dashes (--) with colons (:) in key names.
```csharp
    public class CustomKeyVaultSecretManager : IKeyVaultSecretManager
    {
        public string GetKey(SecretBundle secret)
        {
            var key = secret.SecretIdentifier.Name.Replace("--", ":");
            return key;        
        }
    }
```

However in Orchard Core we are using . or _ so we need a way to distinguish what should be replaced with an underscore (_) vs what should be replace with a colon (:) without have to add an edge case for each word.

For example I want to store the following key in my keyvault, but unfortunately my logic wont know which -- to replace with _ vs : 
OrchardCore--OrchardCore--Media--Azure--ConnectionString

**Comment by JoshLefebvre** [comment]
Can get around it by storing key as 
OrchardCore--OrchardCore111Media111Azure111ConnectionString' 

and using the following in my CustomKeyVaultSecretManager:
`var key = secret.SecretIdentifier.Name.Replace("--", ":").Replace("111", "_");`

But obviously I would like to use something more meaningful than 111.

Source: https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#use-a-key-name-prefix

**Comment by jtkech** [comment]
- Maybe replace first `--` with `:` and then `-` with `_`

      OrchardCore--OrchardCore-Media-Azure--ConnectionString
      => OrchardCore:OrchardCore_Media_Azure:ConnectionString

If we think that a module name may contain a dash (but i don't think so)

- Maybe replace first `---` with `_` and then `--` with `:`

      OrchardCore--OrchardCore---Media---Azure--ConnectionString
      => OrchardCore:OrchardCore_Media_Azure:ConnectionString

**Comment by JoshLefebvre** [comment]
Okay! Yeah that is a lot cleaner! I'll give it a try

**Comment by saciervo** [comment]
Had the same problem. 

I ended up using the `##vso` command syntax to define a pipeline variable with the name `OrchardCore.OrchardCore.Media.Azure.ConnectionString` and the content of the secret as its value . 

On deployment it will be automatically picked up for the JSON transformations.

These are the relevant bits of my yaml file:
```
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'your-subscription'
    KeyVaultName: 'your-key-vault'
    SecretsFilter: 'your-blob-connection'

- task: PowerShell@2
  displayName: 'Write KeyVault secret in variable'
  inputs:
    targetType: 'inline'
    script: 'Write-Host "##vso[task.setvariable variable=OrchardCore.OrchardCore.Media.Azure.ConnectionString]$(your-blob-connection)"'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: '$(Parameters.connectedServiceName)'
    appType: 'webApp'
    WebAppName: '$(Parameters.WebAppName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/$(Parameters.DeploymentPackageName).zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    JSONFiles: 'appsettings.json'
```
