### ISSUE TITLE
Add SQL Server minimum requirements

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#8395]
Add somewhere in the documentation SQL Server minimum requirements.
While we are at it we should also probably investigate minimum requirement for MySQL and PostgreSQL.
Or simply advise to use the current latest versions as it is developped against these.

**Comment by agriffard** [comment]
Can you please list the minimum requirements for each db provider?

**Comment by Skrypt** [comment]
That would take a while to figure out every intricacies between versions.
We develop against latest versions most of the time. We know that right now we have a limitation with SQL Server under 2016. But, I think that the appropriate thing would be to document that we can create SQLDialects for these.

**Comment by deanmarcussen** [comment]
For info the current versions YesSql is tested against.
```        
      image: postgres:11

      mysql:
        image: mysql:8

      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
```

think we're safe to safe MS SQL 2016 here as well, but should probably bring it into the test matrix at some point
